### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Walkman100** [mike-mo/MoreTerra#5]
I am speechless.

![image](https://cloud.githubusercontent.com/assets/5454764/11022900/8de39400-8673-11e5-83a5-839c9c658b5e.png)
Was just trying to run a few EXEs with mono, expecting nothing to work... but there it is... and it worked...

**Comment by TerabyteRex** [comment]
Glad its working well. I don't have a linux setup currently, so I you see any issues, let me know. I'll try and help.

Sent from my Windows Phone

**Comment by Walkman100** [comment]
It seems to work exactly as I remember it on Windows.

**Comment by Pysis868** [comment]
This project seems to be written in Visual Studio, maybe to the .NET framework?  I don't know much about them, but if that is so, maybe it works since people have supported the port to Linux, and even Microsoft as well, I think with Mono.

Anyway, that's cool.  Maybe this issue can be closed now :).

**Comment by Walkman100** [comment]
It's not really an issue, just to let people know that since Terraria runs on Linux now, this tool works too. Also something could be added to the project page, that it could work on Linux with mono?
